#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-only
set -eu
[ -z "${IPKG_INSTROOT:-}" ] || exit 0
mkdir -p /etc/crontabs
touch /etc/crontabs/root
if ! grep -Fq '/bin/v2ray-geodata-updater' /etc/crontabs/root; then
  echo '0 4 * * 0 /bin/v2ray-geodata-updater' >> /etc/crontabs/root
  crontab /etc/crontabs/root
fi
exit 0
